### ISSUE TITLE
[Feature] Employees table

### ISSUE THREAD

**Issue by cjdalan** [cjdalan/SanMiguel#2]
# employees
- Personal information
    - INT **id** auto_increment index
    - INT **user_id** foreign key, reference to users table
    - VARCHAR **first_name**
    - VARCHAR **last_name**
    - VARCHAR **middle_name**
    - DATE **birth_date**   

- Employment status
    - INT **employee_num** index
    - DATETIME **employed_at**
    - TINYINT **employment_status** ['working', 'resigned']
    - INT **position_id** foreign key, reference to positions table
    - VARCHAR **schedule_id** foreign key, reference to schedules tables
    - VARCHAR **salary** might encrypt this
- Employee requirements
    - VARCHAR **sss_id** should encrypt this
    - VARCHAR **pagibig_id** should encrypt this
    - VARCHAR **philhealth_id** should encrypt this
    - VARCHAR **tin_id** should encrypt this

**Comment by aereneth** [comment]
**Table Suggestion**
- Employee
    - INT id (primary key)
    - INT status
    - INT user_id (foreign key *disregard if no employee account)
    - INT position_id (foreign key)
    - DATETIME employment_date (default=current_timestamp)
    - VARCHAR schedule_id (foreign key)
    - VARCHAR/DECIMAL salary
