### ISSUE TITLE
[Feature] Login

### ISSUE THREAD

**Issue by cjdalan** [cjdalan/SanMiguel#3]
- Users should be able to login
- Use **/users/login** route
- Use **werkzeug.security.check_password_hash()** to check for password
- Session should only store the userID, should retrieve user information during **before_request()** and store in g.user
- Use **user** session variable
- If query parameter **next** is not None, redirect user to value of next

**Comment by cjdalan** [comment]
@aereneth 
- Created /core/users.py with login function
- Created /templates/base.html with no framework
- Created /templates/users/login.html

**Comment by aereneth** [comment]
- Created **/core/forms.py** with login validation
- Updated **/templates/base.html** with Bootstrap 4 as temporary framework
- Updated app.py before_request
- Updated **/core/models.py** reusing open connection
- Updated **/core/users.py** include authentication on submit form (should authentication be on separate?)

**Comment by aereneth** [comment]
#c416012
